In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

# one hot representation


In [7]:
one_hot_rep=[one_hot(words,voc_size)for words in sent]
print(one_hot_rep)

[[5155, 1945, 7550, 4171], [5155, 1945, 7550, 7012], [5155, 4094, 7550, 2058], [9561, 9524, 9925, 4505, 5578], [9561, 9524, 9925, 4505, 868], [6094, 5155, 7955, 7550, 2936], [5908, 8714, 8292, 4505]]


# word embedding representation


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5155 1945 7550 4171]
 [   0    0    0    0 5155 1945 7550 7012]
 [   0    0    0    0 5155 4094 7550 2058]
 [   0    0    0 9561 9524 9925 4505 5578]
 [   0    0    0 9561 9524 9925 4505  868]
 [   0    0    0 6094 5155 7955 7550 2936]
 [   0    0    0    0 5908 8714 8292 4505]]


In [16]:
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 33ms/step
[[[-1.88207030e-02  3.26341279e-02  1.84945576e-02 -4.93290909e-02
    2.87495144e-02 -1.09348893e-02 -2.07369458e-02  4.92169298e-02
    4.58104275e-02  5.62331825e-03]
  [-1.88207030e-02  3.26341279e-02  1.84945576e-02 -4.93290909e-02
    2.87495144e-02 -1.09348893e-02 -2.07369458e-02  4.92169298e-02
    4.58104275e-02  5.62331825e-03]
  [-1.88207030e-02  3.26341279e-02  1.84945576e-02 -4.93290909e-02
    2.87495144e-02 -1.09348893e-02 -2.07369458e-02  4.92169298e-02
    4.58104275e-02  5.62331825e-03]
  [-1.88207030e-02  3.26341279e-02  1.84945576e-02 -4.93290909e-02
    2.87495144e-02 -1.09348893e-02 -2.07369458e-02  4.92169298e-02
    4.58104275e-02  5.62331825e-03]
  [ 4.56939079e-02  6.48280233e-03  1.17905252e-02 -4.77701910e-02
    7.53518194e-03  2.26428173e-02  2.74335034e-02 -4.59632650e-02
    5.90543821e-03  1.03362575e-02]
  [ 4.09325995e-02 -3.98248807e-02  2.93884315e-02 -2.45757028e-03
    1.74211599e-02 -4.03372534e

2022-07-30 15:21:33.278297: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 5155, 1945, 7550, 4171], dtype=int32)